nzo_encryptor:
  secret_key: khdk5cjhglihm1f9fdsoihyu5yuè    # Required, max length of 100 characters.
  #secret_iv:  YourSecretIv               # Required only if "random_pseudo_bytes" is FALSE. Max length of 100 characters.
  #cipher_algorithm:                      # optional, default: 'aes-256-ctr'
  #base64_encode:                         # optional, default: TRUE
  #format_base64_output:                  # optional, default: TRUE, used only when 'base64_encode' is set to TRUE
  #random_pseudo_bytes:                   # optional, default: TRUE (generate a random encrypted text output each time => MORE SECURE !)